# name: Cypress Tests

# on: [push]

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.4.2
        
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
      
#       - name: Cypress.io
#         uses: cypress-io/github-action@v4.2.0

name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2

      # - name: Paypal Order Sandbox
      #   uses: cypress-io/github-action@v4.2.0
      #   with:
      #     command: npm run placepaypalorder

      - name: Paypal Credit Card Sandbox
        uses: cypress-io/github-action@v4.2.0
        with:
          command: npm run paypalcreditcard
        